### ISSUE TITLE
How often do you pull?

### ISSUE THREAD

**Issue by Fossil01** [czerwonk/junos_exporter#105]
Loading the metrics page in Chrome takes about 20-30s for my single SRX. So the regular interval of 15s won't work I guess.

What interval is normally used? And is there a way to monitor if IPsec connections are up/connected or should I use something else for that (ping/whatever)?

**Comment by 4xoc** [comment]
Very much depends on the device model and Junos version. Had an SRX with Junos 15.4 that took about 25 seconds for scraping about everything the exporter offers. With 19.4 that time nearly doubled. It's a combination of Junos version and the metrics you want to scrape. I'd recommend a rather long interval than risking scrapes to be aborted because Prometheus' timeout killed the scrape. Lower resolution is better than no data afterall.

Yes you can monitor `junos_ipsec_security_associations_state` and particularly it's absents (when the tunnel is down). An expr in Prometheus could simply be 'absent(junos_ipsec_security_associations_state)'

**Comment by Fossil01** [comment]
Thanks!
