### ISSUE TITLE
Missing config.ignore-targets in v0.10.0 and newer

### ISSUE THREAD

**Issue by maartenbollen** [czerwonk/junos_exporter#203]
Hi,

Seems like the `config.ignore-targets` option is removed from version 0.10.0 and later, is this intended?

**Comment by czerwonk** [comment]
Hi, yes this is intended. As stated in changelog, ``config.ignore-targets`` came with high complexity and special edge case handling and introduced several bugs since there was no device config for the device in several config scenarios (e.g. dynamic labels). The same behavior can be achived with host patterns. You can just define match all device config with host pattern. This ensures an valid device config for every module and does not require special treatment.

```
devices:
  - host: .*
     host_pattern: true
```

**Comment by maartenbollen** [comment]
thanks! i missed out the change log for some reason!
