### ISSUE TITLE
Routing Engine high CPU usage when the exporter is running

### ISSUE THREAD

**Issue by guyellen** [czerwonk/junos_exporter#77]
Cpu usage increase to 100% when the exporter is running. 

![image](https://user-images.githubusercontent.com/25636244/68663992-3ac51480-0548-11ea-9da4-56d0fa627c55.png)

I've tried to run the exporter with minimal modules and I still experience the CPU usage increase.

**Comment by ndom91** [comment]
Seeing the same here.. 
![screenshot_2019-11-12_16-28-39](https://user-images.githubusercontent.com/7415984/68684886-83d99080-0569-11ea-9ca4-7f332bec96fc.png)

172.16.4.141 and 172.16.4.190 do not have the exporter running on them. The others all do. This view is from the previous hour.

**Comment by czerwonk** [comment]
Hi, i will have a look in this. Can you please provides some more information:
* Device Model
* Configured features

Thank you for bringing this to my attention.

**Comment by ndom91** [comment]
@czerwonk in my case they're all ACX4000's, in terms of configured features - what do you mean exactly?

**Comment by guyellen** [comment]
Hi @czerwonk, thanks for reviewing the issue.

Models:
MX5-t
MX80-48t 
MX104

Features (interfaces is disabled) :
  accounting: false
  bgp: false
  environment: true
  firewall: false
  fpc: false
  interface_diagnostic: true
  interface_queue: false
  interfaces: false
  ipsec: false
  isis: false
  l2circuit: false
  ldp: false
  nat: false
  ospf: false
  routes: true
  routing_engine: true
  storage: true

example of show process extensive: 

PID USERNAME        PRI NICE   SIZE    RES STATE    TIME   WCPU COMMAND
   10 root            155   52     0K    16K RUN    6807.1 67.82% idle
98017 root             76    0 56724K 10272K RUN      0:01 48.69% mgd
98016 junos_exporter   52    0 70644K 40400K RUN      0:01 29.21% cli
 2165 root             55    0   106M 35272K select 384.3H  3.37% chassisd
 2349 root              4    0   784M   659M kqread 435.9H  1.07% rpd

**Comment by gaima8** [comment]
This exporter is very CPU heavy by its nature.
Opening a new SSH session for each feature alone is hard work.
Especially on the MX80/MX104 line, the routing engine in those is slow, very slow.

We also monitor using Cacti like @ndom91 appears to, our prometheus interval is 1 minute and cacti interval is 5 minutes, so we generally don't see the spike in the cacti graphs caused by junos_exporter.

https://github.com/l3akage/junos_exporter/tree/HighCPU has a simple patch to hide the spike in CPU usage from itself.
